import java.util.List;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class OrderDetail {
    public String orderID;
    public String customerNameString;
    private List<String> foodOrderList = new ArrayList<>();
    private List<Integer> foodCountList = new ArrayList<>();
    public String orderStatus;

    // This runs when an instance of this class is created
    { createOrderID(); }

    private void createOrderID() {
        // Creation of OrderID is generated by the current timestamp formatted as
        // yyyyMMddHHmm
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMddHHmm");
        orderID = now.format(formatter);
    }

    public String getOrderID() {
        return orderID;
    }

    private void addItemAndQuantity(String menuItem, int itemCount, Menu menu) {
        if (menu.getItemList().contains(menuItem)) {
            if (itemCount > 0) {
                foodOrderList.add(menuItem);
                foodCountList.add(itemCount);
            } else {
                System.out.println("Invalid quantity for " + menuItem + ". Quantity must be greater than 0.");
                return;
            }
        } else {
            System.out.println("No such item as " + menuItem + ". Please check the menu.");
                return;
        }
        System.out.println("Added " + itemCount + " of " + menuItem + " to your order.");

    }

    public static void main(String[] args) {
        Menu inNOut = new Menu();
        OrderDetail order = new OrderDetail();
        order.addItemAndQuantity("Hamburger", 2, inNOut);
    }
}
